### ISSUE TITLE
Git Deploy Version 확인 설정

### ISSUE THREAD

**Issue by keede7** [ask-resume/ask-resume-backend#53]
@132262B @m-dzn 

저번에도 말씀드렸었지만, `Actuator` 의 기능 중 하나이고,  간단한 설정으로 현재 애플리케이션이
어느 시점의 `Commit` 까지 배포되어 적용됐는지 확인이 가능합니다.

- **path : /actuator/info**
```java
  {
   "git":{
	   "branch":"main",
	   "commit":{
	   "id":"754bc78",
	   "time":"2023-01-01T00:00:00Z"
	   }
   }
   ...
  }
```
기본적으로는 이런식으로 볼 수 있다고 합니다.

적시성(?) 이 조금 떨어지긴 하지만 필요하다면,,

**Comment by 132262B** [comment]
해당 기능을 모니터링 페이지에서 UI가 있는 상태로 조회 할 수 있나요?

**Comment by keede7** [comment]
> 해당 기능을 모니터링 페이지에서 UI가 있는 상태로 조회 할 수 있나요?

프로메테우스 수집 대상인지 확인을 해봐야 할 거 같습니다..!

**Comment by 132262B** [comment]
수집 대상인지, 확인 하고 한번 더 코멘트 부탁드리겠습니다!

**Comment by keede7** [comment]
> 수집 대상인지, 확인 하고 한번 더 코멘트 부탁드리겠습니다!

프로메테우스를 활성화 하게 되면 `actuator/prometheus` 엔드포인트가 활성화되는데 
`Git` 설정은 `--/info` 에서 확인이 가능하기 때문에 수집경로에서 제외되네요,
